"""
Reflection Model - 5 Q&A + Narasi MHCM
"""
from sqlalchemy import Column, String, DateTime, Text, Integer, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from database.base import Base


class Reflection(Base):
    """Model untuk menyimpan refleksi (5 pertanyaan + jawaban + narasi)"""
    
    __tablename__ = "reflections"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String(36), ForeignKey("chat_sessions.id"), nullable=False, index=True)
    
    # 5 Reflection Q&A
    question_1 = Column(Text, nullable=True)
    answer_1 = Column(Text, nullable=True)
    
    question_2 = Column(Text, nullable=True)
    answer_2 = Column(Text, nullable=True)
    
    question_3 = Column(Text, nullable=True)
    answer_3 = Column(Text, nullable=True)
    
    question_4 = Column(Text, nullable=True)
    answer_4 = Column(Text, nullable=True)
    
    question_5 = Column(Text, nullable=True)
    answer_5 = Column(Text, nullable=True)
    
    # Completion tracking
    questions_completed = Column(Integer, default=0)  # 0-5
    
    # MHCM Narrative (generated by Gemini in Fase 3)
    mhcm_narrative = Column(Text, nullable=True)
    narrative_zone = Column(String(50), nullable=True)  # Zona hasil narasi
    
    # Tips shown
    tips_ids = Column(JSON, nullable=True)  # List of tip IDs shown
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    
    # Relationships
    session = relationship("ChatSession", back_populates="reflections")
    
    def __repr__(self):
        return f"<Reflection(id={self.id}, completed={self.questions_completed}/5)>"
    
    def get_current_question_index(self) -> int:
        """Get current question index (0-4)"""
        return self.questions_completed
    
    def is_complete(self) -> bool:
        """Check if all 5 questions are answered"""
        return self.questions_completed >= 5
    
    def add_answer(self, question: str, answer: str) -> bool:
        """Add answer for current question"""
        if self.questions_completed >= 5:
            return False
        
        q_idx = self.questions_completed + 1
        setattr(self, f"question_{q_idx}", question)
        setattr(self, f"answer_{q_idx}", answer)
        self.questions_completed += 1
        
        if self.questions_completed >= 5:
            self.completed_at = datetime.utcnow()
        
        return True
    
    def get_all_qa(self) -> list:
        """Get all Q&A as list of dicts"""
        qa_list = []
        for i in range(1, 6):
            q = getattr(self, f"question_{i}")
            a = getattr(self, f"answer_{i}")
            if q:
                qa_list.append({
                    "question_number": i,
                    "question": q,
                    "answer": a
                })
        return qa_list
